---
language: python

python:
  - '3.7'

os: linux
dist: bionic

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - pip install pipenv
  - pipenv install

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
