---
- name: Ensure prometheus dir exists
  become: true
  file:
    path: /opt/prometheus
    recurse: true
    state: directory

- name: Ensure resque-exporter is downloaded
  get_url:
    url: "https://github.com/jobscore/resque-exporter/releases/download/{{resque_exporter_version}}/resque-exporter-{{ resque_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/resque-exporter-{{ resque_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    mode: 0644

- name: Ensure resque-exporter is extracted
  unarchive:
    remote_src: yes
    src: "/tmp/resque-exporter-{{ resque_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/"

- name: Ensure resque-exporter is installed
  copy:
    remote_src: yes
    src: /tmp/resque-exporter
    dest: /opt/prometheus/resque-exporter
    mode: 0755
    owner: root
    group: root
  notify:
    - restart resque-exporter

- name: Ensure resque-exporter service is configured
  become: true
  template:
    dest: /etc/systemd/system/prometheus-resque-exporter.service
    src: resque-exporter-service.j2
  notify:
    - restart resque-exporter

- name: Ensure resque-exporter service is enabled
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: prometheus-resque-exporter
  notify:
    - restart resque-exporter
