---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: solita/ubuntu-systemd
    image_version: 18.04
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
